### ISSUE TITLE
It does not build

### ISSUE THREAD

**Issue by dzenanz** [SimonRit/ITKCudaCommon#8]
If I enable `Module_CudaCommon`, I get:
```text
CMake Error at CMake/ITKModuleMacros.cmake:473 (add_library):
  Target "CudaCommon" links to target "CUDA::cudart" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  Modules/Remote/CudaCommon/src/CMakeLists.txt:12 (itk_module_add_library)
```
and
```text
CMake Error at CMake/ITKModuleTest.cmake:62 (add_executable):
  Target "CudaCommonTestDriver" links to target "CUDA::cudart" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  Modules/Remote/CudaCommon/test/CMakeLists.txt:7 (CreateTestDriver)
```
My `OPENCL_LIBRARIES` is `C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.2/lib/x64/OpenCL.lib`.

**Comment by dzenanz** [comment]
I don't have a CMake variable in ITK configuration called `CUDA_NVCC_EXECUTABLE`. My system environment has `CUDA_PATH` and it is set to `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2`. `nvcc` is available on the path and it is in `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin\nvcc.exe`. Is `CUDA_NVCC_EXECUTABLE` a secret setting? Is it supposed to be that way?

**Comment by SimonRit** [comment]
According to the documentation of [FindCUDAToolkit](https://cmake.org/cmake/help/latest/module/FindCUDAToolkit.html), setting CUDA_PATH should work. Which version of cmake are you using?

**Comment by dzenanz** [comment]
CMake 3.21.4.

**Comment by SimonRit** [comment]
We (@LucasGandel and I) have run into similar issues before and I actually don't know what's wrong. Maybe something is wrong in [itk-module-init.cmake](https://github.com/SimonRit/ITKCudaCommon/blob/master/itk-module-init.cmake)... On Linux, if I run
```
CUDA_PATH=/home/srit/Downloads/cuda116 ~/Downloads/cmake-3.21.4-linux-x86_64/bin/cmake ../itk -DModule_CudaCommon=ON
```
it works...

**Comment by SimonRit** [comment]
I did a  Windows test:
```
C:\Users\RTK\Downloads\cmake-3.21.4-windows-x86_64\bin\cmake ../ITK-master -DModule_CudaCommon=ON
```
with, in my env variables,
```
CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1
Path=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\bin
```
and it works. I don't know what could be the reason for your failure but might it be a conflicting env variable? For example, is `CUDAToolkit_ROOT` set?

**Comment by SimonRit** [comment]
I don't understand why you had `CMAKE_CUDA_COMPILER` to `NOTFOUND`. Is it the same if you start from scratch?
Looking at https://gitlab.kitware.com/cmake/cmake/-/issues/21523, maybe there is a problem with you MSVC configuration?

**Comment by dzenanz** [comment]
It must have been years since I last had a problem with MSVC configuration. I doubt that's it. This is not important enough to me right now to do a clean build - I might try it sometime later.

**Comment by SimonRit** [comment]
Thank you for your efforts already. I honestly don't know what could be the problem here. It might be helpful to test if `FindCUDAToolkit` works in a small separate project? If not, it would mean that the problem is not in the CudaCommon module. If yes, you could then check the differences between the `CMakeCache.txt` files?

**Comment by SimonRit** [comment]
Please re-open if you're still not able to build it.

**Comment by dzenanz** [comment]
I tried it again with 5.3.0, and it builds now.

**Comment by SimonRit** [comment]
Thanks a lot for checking!
